
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Product {
			/**
			* FaceBook Shop

				If enabled then this product will be affiliated by Face Book
			* @group custom - custom
			* @source [attribute](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#5) | [group](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#43)
			*/
			faceBookShop: boolean | null;

			/**
			* Google Shop

				If enabled then this product will be affiliated by Google Shop
			* @group custom - custom
			* @source [attribute](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#16) | [group](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#44)
			*/
			googleShop: boolean | null;

			/**
			* Instagram Shop

				If enabled then this product will be affiliated by Instagram Shop
			* @group custom - custom
			* @source [attribute](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#27) | [group](file:e:\github-vendor\MultiVendor\link_multivendor\metadata\main\system-objecttype-extensions.xml#42)
			*/
			instagramShop: boolean | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}